App\Entity\Link:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: shortLink

    properties:
        longLink:
            - Url: { protocols: [http, https], relativeProtocol: false}

        shortLink:
          - NotEqualTo: link

