App\Entity\Link:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: shortLink

    properties:
        longLink:
            - Url: { protocols: [http, https], relativeProtocol: false}

        shortLink:
          - NotEqualTo: link
          - NotEqualTo: register
          - NotEqualTo: login
          - NotEqualTo: logout
          - Regex:
              pattern: '/\W/'
              match: false

App\Entity\User:
    properties:
        username:
          - Regex:
              pattern: '/\s/'
              match: false
          - Regex:
              pattern: '/\W/'
              match: false